name: main
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: main
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_password: ${{ secrets.PROXY_PASSWORD }}
          script: |
            cd /var/www/html/laravelapp/
            git pull origin main
            git add .
            git commit -m "ServerUpdate"
            git push origin main
